import Image from 'next/image'
import Data from './Data'
import type { Metadata } from 'next';
import FormField from '@/components/FormField';
import OptionalRenderCards from '@/components/Cards/OptionalRenderCards';

export const metadata : Metadata = {
  title: 'Dall 2.0',
  description: 'This is an AI image generator website'
}




export default function Home() {

  const handleChange = ()=>{
    
  }

  return (
    <main className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
        <p className='mt-2 text-[#666e75] max-w-[500px] text-[16px] '>
          Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
        </p>
      </div>

      <div className='mt-16'>
          <OptionalRenderCards/>
      </div>
      
          {/* <FormField lableName='Search Post' placeholder='Search posts' name='post' type='text'/>
      </div>

      <div className='mt-10'> */}

    </main>
  )
}
